version: '3.4'

services:
  react-frontend:
    container_name: speakfluid-frontend    
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ./frontend:/home/node/app:cached
    working_dir: /home/node/app
    ports:
      - '80:80'
      - '443:443'
    depends_on: 
      - spring-middleware

  spring-middleware:
    container_name: speakfluid-backend    
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
